name: Build & Deploy

on:
  push:
    branches:
      - main  # Runs when pushing to 'main'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest  # Modify based on your testing framework

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS S3
        run: aws s3 sync . s3://your-bucket --delete

      - name: Deploy AWS Lambda Function
        run: aws lambda update-function-code --function-name my-lambda --zip-file fileb://deployment.zip

      - name: Start EC2 Instance
        run: aws ec2 start-instances --instance-ids i-09f1f6a4f46d99e8e

      - name: Stop EC2 Instance (Optional)
        run: aws ec2 stop-instances --instance-ids i-09f1f6a4f46d99e8e
